import { Schema,model,models } from "mongoose";


const HomeStaySchema = new Schema(
    {
        isUrbanOrRular: { 
            type: String 
        },
        isPrivateOrGovt: { 
            type: String 
        },
        isNormalOrHeritage:{
            type: String
        },
        state:{
            type: String
        },
        district:{
            type: String
        },
        constituency:{
            type: String
        },
        villageOrTown:{
            type: String
        },
        mcnpgpuward:{
            type:String
        },
        address:{
            type:String
        },
        homestayName:{
            type:String
        },
        ownerName:{
            type:String
        },
        qualification:{
            type:String
        },
        gender:{
            type:String
        },
        manager:{
            type:String
        },
        isRegistredWithDot:{
            type:String
        },
        registrationNumberDot:{
            type:String
        },
        establishmentDate:{
            type:Date
        },
        renewDateDot:{
            type:Date
        },
        isRegisteredWithLocal:{
            type:String
        },
        registrationLocal:{
            type:String
        },
        renewDateLocal:{
            type:Date
        },
        roomNumbers:{
            type:Number
        },
        singleRoom:{
            type:Number
        },
        doubleRoom:{
            type:Number
        },
        carryingCapacity:{
            type:Number
        },
        localStaff:{
            type:Number
        },
        otherStaff:{
            type:Number
        },
        trainedStaff:{
            type:Number
        },
        nontrainedStaff:{
            type:Number
        },
        villageTour:{
            type:String
        },
        birdWatching:{
            type:String
        },
        organicFarming:{
            type:String
        },
        anyOtherActivity:{
            type:String
        },
        nearByAttraction:[{
            name:{
                type:String
            },
            distance:{
                type:Number
            }
        }],
        transportation:{
            type:String
        },
        accessibility:{
            type:String
        },
        wasteDisposal:{
            isYesorNo:{
                type:String
            },
            description:{
                type:String
            }
        },
        drinkingWater:{
            isYesorNo:{
                type:String
            },
            description:{
                type:String
            }
        },
        firstAid:{
            isYesorNo:{
                type:String
            },
            description:{
                type:String
            }
        },
        ecoFriendly:{
            isYesorNo:{
                type:String
            },
            description:{
                type:String
            }
        },
        cleaning:{
            isYesorNo:{
                type:String
            },
            description:{
                type:String
            }
        },
        makeMyTrip:{
            isRegistered:{
                type:String
            },
            percentage:{
                type:Number
            }
        },
        agoda:{
            isRegistered:{
                type:String
            },
            percentage:{
                type:Number
            }
        },
        airBnb:{
            isRegistered:{
                type:String
            },
            percentage:{
                type:Number
            }
        },
        goIbibo:{
            isRegistered:{
                type:String
            },
            percentage:{
                type:Number
            }
        },
        otherOnline:{
            type:String
        },
        isRecordMaintained:{
            type:String
        },
        isManualorDigital:{
            type:String
        },
        occupancyInPeak:{
            type:Number
        },
        occupancyInLean:{
            type:Number
        },
        touristInYear:{
            type:Number
        },
        domesticTourist:{
            type:Number
        },
        
        foreignTourist:{
            type:Number
        },
        isDigitalized:{
            type:String
        },
        digitalEquiment:{
            type:String
        },
        digitalSupport:{
            type:String
        },
        isAccountMaintained:{
            type:String
        },
        isAccountDigital:{
            type:String
        },
        email:{
            type:String
        },
        website:{
            type:String
        },
        contact:{
            type:String
        },
        signature:{
            type:String
        },
        homestayImages:[
            {
                type:String
            }
        ]
        ,
        isStatus: { type: Number, default: 0 },
        createdAt: { type: Date, default: Date.now },
        createdBy: { 
            type: String
        },
        modifiedBy: { 
            type: String
        }
    }
);
const homeStay = models.homestay  || model('homestay',HomeStaySchema)

export default  homeStay; 