const  homestayDummyData =[
    {
        isUrbanOrRular: 'Rular',
        isPrivateOrGovt: 'Private',
        isNormalOrHeritage:'Normal',
        state:"Sikkim",
        district:"Gangtok",
        constituency:"Arithang",
        homestayName:"My Homestay 1",
        ownerName:"Mr A",
        qualification:"Graduate",
        gender:'Male',
        isRegistredWithDot:'Yes',
        registrationNumberDot:"DOT2000",
        establishmentDate:"2000-05-12",
        renewDateDot:"2002-05-12",
        isRegisteredWithLocal:'Yes',
        registrationLocal:"LOC2000",
        renewDateLocal:"2000-05-12",
        email:"",
        contact:"8001664823",
        isStatus: 1,
        createdBy:null
    },//1
    {
        isUrbanOrRular: 'Urban',
        isPrivateOrGovt: 'Private',
        isNormalOrHeritage:'Normal',
        state:"Sikkim",
        district:"Gangtok",
        constituency:"Gangtok",
        homestayName:"Hello",
        ownerName:"Mrs B",
        qualification:"Post Graduate",
        gender:'Female',
        isRegistredWithDot:'No',
        registrationNumberDot:"",
        establishmentDate:"",
        renewDateDot:"",
        isRegisteredWithLocal:'Yes',
        registrationLocal:"LOC2005",
        renewDateLocal:"2005-08-12",
        email:"",
        contact:"1111111111",
        isStatus: 1,
        createdBy:null
    },//2
    {
        isUrbanOrRular: 'Urban',
        isPrivateOrGovt: 'Government',
        isNormalOrHeritage:'Heritage',
        state:"Sikkim",
        district:"Gangtok",
        constituency:"Shyari",
        homestayName:"Beauty Hill",
        ownerName:"C",
        qualification:"Secondary",
        gender:'Male',
        isRegistredWithDot:'Yes',
        registrationNumberDot:"DOT2012",
        establishmentDate:"2012-08-12",
        renewDateDot:"2012-08-12",
        isRegisteredWithLocal:'Yes',
        registrationLocal:"LOC2008",
        renewDateLocal:"2008-02-22",
        email:"",
        contact:"9999999999",
        isStatus: 1,
        createdBy:null
    },//3
    {
        isUrbanOrRular: 'Rular',
        isPrivateOrGovt: 'Government',
        isNormalOrHeritage:'Normal',
        state:"Sikkim",
        district:"Gangtok",
        constituency:"Shyari",
        homestayName:"Beauty Hill",
        ownerName:"C",
        qualification:"Illetrate",
        gender:'Female',
        isRegistredWithDot:'Yes',
        registrationNumberDot:"DOT2012",
        establishmentDate:"2012-08-12",
        renewDateDot:"2012-08-12",
        isRegisteredWithLocal:'No',
        registrationLocal:"LOC2008",
        renewDateLocal:"2008-02-22",
        email:"",
        contact:"9999999999",
        isStatus: 1,
        createdBy:null
    },//4
    {
        isUrbanOrRular: 'Rular',
        isPrivateOrGovt: 'Private',
        isNormalOrHeritage:'Normal',
        state:"Sikkim",
        district:"Soreng",
        constituency:"Shyari",
        homestayName:"Beauty Hill",
        ownerName:"C",
        qualification:"Doctrate",
        gender:'Female',
        isRegistredWithDot:'Yes',
        registrationNumberDot:"DOT2012",
        establishmentDate:"2012-08-12",
        renewDateDot:"2012-08-12",
        isRegisteredWithLocal:'No',
        registrationLocal:"LOC2008",
        renewDateLocal:"2008-02-22",
        email:"",
        contact:"9999999999",
        isStatus: 1,
        createdBy:null
    }
] 

export default homestayDummyData